# Generated by Django 2.2.28 on 2023-11-18 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('manaCost', models.CharField(max_length=100)),
                ('releaseDate', models.DateField()),
                ('cmc', models.IntegerField()),
                ('colors', models.CharField(max_length=100)),
                ('types', models.CharField(max_length=100)),
                ('supertypes', models.CharField(max_length=100)),
                ('subtypes', models.CharField(max_length=100)),
                ('rarity', models.CharField(max_length=100)),
                ('text', models.CharField(max_length=100)),
            ],
        ),
    ]
