# Generated by Django 4.2.7 on 2023-11-24 02:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20231119_1814'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeckCard',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('quantity', models.IntegerField()),
            ],
            options={
                'ordering': ['deckId'],
            },
        ),
        migrations.CreateModel(
            name='DeckIndex',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('owner', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('format', models.CharField(max_length=100)),
                ('size', models.IntegerField()),
                ('dateCreated', models.DateTimeField(auto_now_add=True)),
                ('dateUpdated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='card',
            options={'ordering': ['name']},
        ),
        migrations.DeleteModel(
            name='Deck',
        ),
        migrations.AddField(
            model_name='deckcard',
            name='cardId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.card'),
        ),
        migrations.AddField(
            model_name='deckcard',
            name='deckId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.deckindex'),
        ),
    ]
