# Generated by Django 4.2.7 on 2023-11-30 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_deckcard_deckindex_alter_card_options_delete_deck_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deckindex',
            name='size',
        ),
    ]
