# Generated by Django 4.2.7 on 2023-11-30 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_deckindex_size'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='deckcard',
            constraint=models.UniqueConstraint(fields=('deckId', 'cardId'), name='unique_deck_card'),
        ),
    ]
