# Generated by Django 4.2.7 on 2023-11-30 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_deckcard_unique_deck_card'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deckcard',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
