# Generated by Django 4.2.7 on 2023-11-30 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_deckcard_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deckcard',
            name='id',
            field=models.IntegerField(auto_created=True, primary_key=True, serialize=False, unique=True),
        ),
    ]
