# Generated by Django 4.2.7 on 2023-11-30 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_deckcard_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='deckindex',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
